version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Testing CircleCI Configuration
          command: echo "Hello OSource"
